name: UBC Supermileage
description: The University of British Columbia Supermileage Team
url: http://supermileage.ca
dateformat: "%-d %B, %Y"
title: UBC Supermileage
paginate: 10
paginate_path: "/archive/page:num/"
gems:
 - jekyll-paginate